import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Open_Sans} from "@next/font/google"

const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  )
}
